#!/usr/bin/env node
/**
 * Generates MAP.md — the machine-maintained repo map. Everything structural is
 * derived from the tree and package.json. The only hand-written input is
 * scripts/map-areas.json, which supplies the one-line purpose of each
 * directory — that cannot be derived from code.
 *
 *   node scripts/generate-map.mjs            write MAP.md
 *   node scripts/generate-map.mjs --check    exit 1 if it is stale or an
 *                                            area has no description
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const UNDESCRIBED = '⚠️ UNDESCRIBED — add an entry to scripts/map-areas.json';
const SKIP_DIRS = new Set(['node_modules', 'dist', 'out', '.git', 'coverage', '.astro']);
const CODE_EXT = /\.(ts|mjs)$/;

const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const readJson = (p) => JSON.parse(read(p));
const posix = (p) => p.split('\\').join('/');
const exists = (p) => {
  try {
    return statSync(join(ROOT, p)).isDirectory();
  } catch {
    return false;
  }
};

// ---------------------------------------------------------------- area scan

/** Directories containing at least one .ts/.mjs file, excluding test/. */
function scanAreas() {
  const roots = [];
  for (const group of ['packages', 'apps']) {
    let entries;
    try {
      entries = readdirSync(join(ROOT, group));
    } catch {
      continue;
    }
    for (const name of entries) {
      for (const sub of ['src', 'bin', 'scripts']) {
        const p = `${group}/${name}/${sub}`;
        if (exists(p)) roots.push(p);
      }
    }
  }

  const areas = [];
  const walk = (rel) => {
    let entries;
    try {
      entries = readdirSync(join(ROOT, rel), { withFileTypes: true });
    } catch {
      return;
    }
    const files = entries.filter((e) => e.isFile() && CODE_EXT.test(e.name)).map((e) => e.name);
    if (files.length) areas.push({ dir: posix(rel), files: files.length });
    for (const e of entries) {
      if (e.isDirectory() && !SKIP_DIRS.has(e.name)) walk(join(rel, e.name));
    }
  };
  roots.forEach(walk);
  return areas.sort((a, b) => a.dir.localeCompare(b.dir));
}

// ------------------------------------------------------------- export scan

/**
 * Parses a package's index.ts into { group, symbols[] } records. Groups come
 * from the `// Section comment` lines the index file already uses.
 */
function scanExports(pkgDir) {
  let src;
  try {
    src = read(`${pkgDir}/src/index.ts`);
  } catch {
    return [];
  }

  const groups = [];
  let label = 'Exports';
  const flat = src.replace(/export\s*\{[^}]*\}\s*from/g, (m) => m.replace(/\s+/g, ' '));

  for (const line of flat.split('\n')) {
    const t = line.trim();
    if (!t) continue;

    const comment = t.match(/^\/\/\s*(.+)$/);
    if (comment && !comment[1].startsWith('/')) {
      const text = comment[1].trim();
      if (text.length <= 120 && !text.endsWith('.')) label = text;
      continue;
    }

    const named = t.match(/^export\s*\{(.+?)\}\s*from\s*['"](.+?)['"]/);
    const star = t.match(/^export\s*\*\s*from\s*['"](.+?)['"]/);
    if (!named && !star) continue;

    const from = (named ? named[2] : star[1]).replace(/^\.\//, '').replace(/\.js$/, '');
    const symbols = named
      ? named[1]
          .split(',')
          .map((s) => s.trim().replace(/^type\s+/, '').split(/\s+as\s+/)[0].trim())
          .filter(Boolean)
      : ['*'];

    let g = groups.find((x) => x.label === label);
    if (!g) groups.push((g = { label, symbols: [], from: new Set() }));
    g.symbols.push(...symbols);
    g.from.add(from);
  }
  return groups;
}

// ------------------------------------------------------------------ render

const esc = (s) => String(s).replace(/\|/g, '\\|');
const HEADER = '<!-- Generated by scripts/generate-map.mjs — do not edit by hand. Run `npm run map`. -->\n';

function renderMap({ areas, descriptions, exportsByPkg, pkg }) {
  const out = [];
  out.push(HEADER);
  out.push('# Repo map\n');
  out.push(
    `Structural index of \`${pkg.name}\`. **Read this to locate code** — it is regenerated from the tree, so it cannot drift.\n`,
  );
  out.push(
    'For *how* a subsystem behaves and what has already gone wrong in it, read `findings/`. For user-facing behavior, read `docs/`, `packages/compiler/GRAMMAR.md`, and `site/` — but do not read those to learn the code.\n',
  );

  out.push('\n## Entry points\n');
  out.push('| Entry | Path |');
  out.push('|---|---|');
  for (const a of areas.filter((x) => /\/bin$/.test(x.dir))) {
    for (const f of listCodeFiles(a.dir)) out.push(`| CLI — \`${basename(f, '.ts')}\` | \`${a.dir}/${f}\` |`);
  }
  for (const a of areas.filter((x) => /\/scripts$/.test(x.dir))) {
    for (const f of listCodeFiles(a.dir)) out.push(`| Script — \`${f}\` | \`${a.dir}/${f}\` |`);
  }

  out.push('\n## Areas\n');
  let section = '';
  out.push('| Directory | Files | Purpose |');
  out.push('|---|---:|---|');
  for (const a of areas) {
    const parts = a.dir.split('/');
    const top = parts.slice(0, 2).join('/');
    if (top !== section) {
      section = top;
      out.push(`| **${top}** | | |`);
    }
    out.push(`| \`${a.dir}\` | ${a.files} | ${esc(descriptions[a.dir] ?? UNDESCRIBED)} |`);
  }

  out.push('\n## Package exports\n');
  for (const [pkgDir, groups] of Object.entries(exportsByPkg)) {
    if (!groups.length) continue;
    const name = readJson(`${pkgDir}/package.json`).name;
    out.push(`\n### \`${name}\` — \`${pkgDir}/src/index.ts\`\n`);
    out.push('| Group | Symbols |');
    out.push('|---|---|');
    for (const g of groups) {
      const syms = [...new Set(g.symbols)];
      const shown = syms.includes('*')
        ? `everything from ${[...g.from].map((f) => `\`${f}\``).join(', ')}`
        : syms.map((s) => `\`${s}\``).join(', ');
      out.push(`| ${esc(g.label)} | ${esc(shown)} |`);
    }
  }

  out.push('\n## npm scripts\n');
  out.push('| Script | Runs |');
  out.push('|---|---|');
  for (const [name, cmd] of Object.entries(pkg.scripts ?? {})) {
    const short = cmd.length > 90 ? `${cmd.slice(0, 87)}…` : cmd;
    out.push(`| \`npm run ${name}\` | \`${esc(short)}\` |`);
  }
  out.push('');
  return out.join('\n');
}

function listCodeFiles(dir) {
  try {
    return readdirSync(join(ROOT, dir)).filter((f) => CODE_EXT.test(f));
  } catch {
    return [];
  }
}

// ------------------------------------------------------------------ main

function main() {
  const descriptions = readJson('scripts/map-areas.json');
  const areas = scanAreas();
  const pkg = readJson('package.json');

  const exportsByPkg = {};
  try {
    for (const p of readdirSync(join(ROOT, 'packages'))) {
      exportsByPkg[`packages/${p}`] = scanExports(`packages/${p}`);
    }
  } catch {
    /* no packages/ dir */
  }

  const missing = areas.filter((a) => !descriptions[a.dir]).map((a) => a.dir);
  const content = renderMap({ areas, descriptions, exportsByPkg, pkg });

  let current = null;
  try {
    current = read('MAP.md');
  } catch {
    /* new file */
  }

  if (CHECK) {
    let failed = false;
    if (current !== content) {
      console.error('MAP.md is stale. Run `npm run map` and commit the result.');
      failed = true;
    }
    if (missing.length) {
      console.error('\nDirectories with no purpose in scripts/map-areas.json:');
      for (const d of missing) console.error(`  ${d}`);
      console.error('\nAdd a one-line purpose for each.');
      failed = true;
    }
    if (failed) process.exit(1);
    console.log(`map ok — ${areas.length} areas`);
    return;
  }

  if (current !== content) {
    writeFileSync(join(ROOT, 'MAP.md'), content);
    console.log('updated MAP.md');
  }

  if (missing.length) {
    console.warn(`\n${missing.length} directories have no purpose in scripts/map-areas.json:`);
    for (const d of missing) console.warn(`  ${d}`);
    console.warn('They are marked UNDESCRIBED in MAP.md and will fail `npm run map -- --check`.');
  }
}

main();
